"""add phone number

Revision ID: c3f0e7eb60ba
Revises: b34a21da0faa
Create Date: 2022-12-19 13:32:16.921562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f0e7eb60ba'
down_revision = 'b34a21da0faa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
